services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-wallet-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
    - ./:/var/www
    networks:
    - mini-wallet-network

  nginx:
    image: nginx:alpine
    container_name: mini-wallet-nginx
    restart: unless-stopped
    ports:
    - "8000:80"
    volumes:
    - ./:/var/www
    - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
    - app
    networks:
    - mini-wallet-network

  mysql:
    image: mysql:8.0
    container_name: mini-wallet-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mini_wallet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: mini_wallet
    volumes:
    - mysql_data:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
    - mini-wallet-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: mini-wallet-redis
    restart: unless-stopped
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
    networks:
    - mini-wallet-network

  node:
    image: node:20-alpine
    container_name: mini-wallet-node
    working_dir: /var/www
    volumes:
    - ./:/var/www
    ports:
    - "5173:5173"
    command: sh -c "tail -f /dev/null"
    networks:
    - mini-wallet-network

networks:
  mini-wallet-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: